Repository gardener/gardener-metrics-exporter, pull requests merged in 2020-11, with the labels that each got.

#37 Remove metric `garden_shoot_response_duration_milliseconds`
  README.md
  pkg/metrics/metrics.go
  pkg/metrics/shoot.go
  pkg/template/template.go
Labels: needs/ok-to-test, needs/review, size/s

#39 Format Readme according to remark-lint and fix typo
  README.md
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#42 Use golang 1.15 for ci pipeline PRs
  .ci/pipeline_definitions
Labels: needs/ok-to-test, size/xs

#43 Enrich shoot metrics
  .gitignore
  Makefile
  pkg/metrics/metrics.go
  pkg/metrics/shoot.go
Labels: needs/ok-to-test, size/s

#44 Improve formatting
  cmd/gardener-metrics-exporter/app.go
  pkg/metrics/metrics.go
  pkg/metrics/plant.go
  pkg/metrics/project.go
  pkg/metrics/seed.go
  pkg/metrics/shoot.go
  pkg/metrics/types.go
Labels: needs/ok-to-test, needs/second-opinion, size/l
