Repository gardener/gardener-metrics-exporter, pull requests merged in 2021-07, with the labels that each got.

#53 fix bug with empty/duplicate condition in shoot and seed
  pkg/metrics/seed.go
  pkg/metrics/shoot.go
Labels: reviewed/lgtm, size/xs

#54 Upgrade dependencies
  Makefile
  go.mod
  go.sum
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#55 Add initial managed seed support
  cmd/gardener-metrics-exporter/app.go
  go.sum
  pkg/metrics/managed_seed.go
  pkg/metrics/metrics.go
  pkg/metrics/shoot.go
  pkg/metrics/types.go
  pkg/metrics/utils.go
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#57 Add unit tests
  pkg/metrics/managed_seed.go
  pkg/metrics/managed_seed_test.go
Labels: needs/ok-to-test, needs/review, reviewed/ok-to-test, size/s

#58 Upgrade dependencies
  go.mod
  go.sum
Labels: needs/ok-to-test, needs/review, size/s

#59 Add managedseeds to RBAC
  charts/gardener-metrics-exporter/templates/rbac.yaml
Labels: needs/review, size/xs

#60 Use go 1.16
  Dockerfile
  go.mod
Labels: needs/ok-to-test, needs/review, size/xs
