Repository gardener/gardener-metrics-exporter, pull requests merged in 2021-09, with the labels that each got.

#62 support digests
  charts/gardener-metrics-exporter/templates/_helpers.tpl
  charts/gardener-metrics-exporter/templates/deployment-metrics-exporter.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#64 Update dependencies
  go.mod
  go.sum
Labels: needs/review, reviewed/ok-to-test, size/s

#65 Update ci image
  .ci/pipeline_definitions
Labels: needs/review, size/xs

#66 Update go mod
  go.mod
Labels: needs/review, size/s
