Repository gardener/gardener-metrics-exporter, pull requests merged in 2022-05, with the labels that each got.

#70 Check for user errors
  go.mod
  go.sum
  pkg/metrics/shoot.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#71 Add the k8s version to the garden_seed_info metric
  pkg/metrics/metrics.go
  pkg/metrics/seed.go
Labels: needs/ok-to-test, needs/review, size/xs

#72 Update prometheus/client_golang to v1.12.2
  go.mod
  go.sum
Labels: needs/review, needs/second-opinion, size/xl
