Repository gardener/gardener-metrics-exporter, pull requests merged in 2023-02, with the labels that each got.

#83 Remove the use of the enableBasicAuthentication field
  dashboards/shoot-customization-dashboard.json
  pkg/metrics/shoot_customization.go
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#85 Add migrate and restore types to ShootOperations
  pkg/metrics/shoot.go
Labels: reviewed/lgtm, size/xs

#82 Extended HELM Chart by a couple best practices
  charts/gardener-metrics-exporter/charts/runtime/templates/deployment.yaml
  charts/gardener-metrics-exporter/values.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/s
