Repository gardener/gardener-metrics-exporter, pull requests merged in 2024-11, with the labels that each got.

#112 Add cost_object_type label to garden_shoot_info metric
  pkg/metrics/metrics.go
  pkg/metrics/shoot.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#113 Skip burnt version
  VERSION
Labels: needs/review, reviewed/ok-to-test, size/xs

#114 Skip burnt version
  VERSION
Labels: needs/review, size/xs
